### ISSUE TITLE
HTML output is empty

### ISSUE THREAD

**Issue by wneuhaus** [ivnvxd/arc-export#1]
Running the script produces an empty HTML bookmark file.

```
% python3 main.py          
Reading JSON...
> Found StorableSidebar.json in current directory.
Getting spaces...
> Found 1 spaces.
Converting to bookmarks...
> Found 0 bookmarks.
Converting bookmarks to HTML...
> HTML converted.
Writing HTML...
> HTML written to arc_bookmarks_2023_12_05.html.
Done!
```

Size of the input file: `9265746 Dec  5 15:48 StorableSidebar.json`.

I'm using the following version of Arc: Version 1.19.1 (43687)

**Comment by ivnvxd** [comment]
Do you have pinned tabs in that one space? It does not export all open tabs, only the pinned ones. And is the output the same when running the app without copying `StorableSidebar.json` to the current directory?

**Comment by wneuhaus** [comment]
I have 3 spaces, 2 of them with pinned tabs, and one without any. Could it be that the script only checks the empty one? And indeed, I've run it without copying the json to the working directory but it was the same issue.

**Comment by ivnvxd** [comment]
For some reason, it doesn't see all 3 spaces. And yes, probably it checks only the empty one, but the problem is why it does not see the two remaining spaces. It's hard to tell without your `StorableSidebar.json` file.
I've just tried on the same last Arc version 1.19.1 and it worked fine for me. Have you tried this [https://arc-export.oliviacodes.dev/](https://arc-export.oliviacodes.dev/) exporter?

**Comment by wneuhaus** [comment]
Unfortunately, uploading the json to arc-export is not an option for me. In the meantime, I've removed the empty space, hence only 2 with pinned tabs, but the output is exactly the same. My json seems to be pretty large (9.26MB), could that have an impact? Is there a toggle to enable debugging on your script? Unfortunately, I'm not familiar with Phyton.

**Comment by wneuhaus** [comment]
I'm puzzled. I did run the script again, adding the -v flag and to my surprise, the bookmarks file was successfully populated. Tested again without the -v flag and it works as well. I have no idea what happened. The json remained untouched.

**Comment by craigschwall** [comment]
The same issue is occurring for me. I have tried both methods listed in the README with the same result. 

```
Reading JSON...
> Found StorableSidebar.json in current directory.
Getting spaces...
> Found 1 spaces.
Converting to bookmarks...
> Found 0 bookmarks.
Converting bookmarks to HTML...
> HTML converted.
Writing HTML...
> HTML written to arc_bookmarks_2024_03_27.html.
Done!
```

**Comment by ivnvxd** [comment]
Could you please share the StorableSidebar.json file with me? I realize this is private information, but I'm afraid I just can't help otherwise.
> The same issue is occurring for me. I have tried both methods listed in the README with the same result.
