### ISSUE TITLE
Could you do this for for ARC windows version?

### ISSUE THREAD

**Issue by Alexma03** [ivnvxd/arc-export#7]
It will be awesome to use this tool in windows

Thank you devs

**Comment by ivnvxd** [comment]
I'd love to help, but I don't have a windows computer available.
Try this: look for the `StorableSidebar.json` file in `C:\Users\<your username>\AppData\Local\Packages\TheBrowserCompany.Arc\LocalCache\Local\Arc`, place it in the directory with the script and run the script. Hope it helps.

**Comment by kamildemocko** [comment]
I just created a pull request with support for Windows. Hope this helps.

**Comment by ivnvxd** [comment]
Closed with #8 
Thank you! Tested on Mac — works as before.
